#!/usr/bin/python
import subprocess, os, re
RUN_PATH = os.getcwd()

debug_files = ["debug/DebugRNG.js"]

lint_errors = []
def runUnitTests():
	pass

def runAcceptanceTest():
	pass

def lintFile(filename):
	"""Runs jshint to check the syntax of the file for goodness"""
	global lint_errors
	try:
		out = subprocess.check_output(["jshint",filename],shell=True)
			
	except subprocess.CalledProcessError as error:
		output_lines = re.findall(r'(.*)\n',error.output)
		lint_errors.extend([line for line in output_lines if line.find(filename) == 0])

def printLintErrors():
	"""If lint errors have been found, prints them."""
	if len(lint_errors) > 0:
		print "LINT ERRORS"
		for error in lint_errors:
			print "   ",error

if __name__ == "__main__":
	[lintFile(filename) for filename in debug_files]
	printLintErrors()